config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts, only: [:index, :new, :create]
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :favorites

  # 以下を記述
  def favorite_find(post_id)
    favorites.where(post_id: post_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :post_find

  def create
    Favorite.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:id])
    favorite.destroy
  end

  private

  def post_find
    @post = Post.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    user = User.find(params[:id])
    return redirect_to root_path unless current_user.id ==  user.id
    @user_favorites = user.favorites
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
document.getElementById("post_<%= @post.id %>").innerHTML = '<%= j(render @post) %>'

app/views/favorites/destroy.js.erb
document.getElementById("post_<%= @post.id %>").innerHTML = '<%= j(render @post) %>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavoriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<%= post.title %>
<% if user_signed_in? && current_user != post.user %>
  <% if current_user.favorite_find(post.id) %>
    <%= link_to 'お気に入りをはずす', destroy_favorite_path(post.id), method: :delete, remote: true %>
  <% else %>
    <%= link_to 'お気に入り登録する', create_favorite_path(post.id), method: :post, remote: true %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <%= link_to '投稿ページへ', new_post_path %>
  <%= link_to 'お気に入り一覧', user_path(current_user.id)%>
<% else %>
  <%= link_to 'ログイン', new_user_session_path %>
  <%= link_to '新規登録', new_user_registration_path %>
<% end %>

<div class="post">
<h2>投稿一覧</h2>
<p>↓↓↓</p>
  <% @posts.reverse_each do |post| %>
    <div id="post_<%= post.id %>">
      <%= render 'post', post: post%>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= f.text_field :title %>
  <%= f.submit '投稿する' %>
<% end %>

app/views/users/show.html.erb
<% @user_favorites.reverse_each do |favorite| %>
  <div>
    <%= favorite.post.title %>
  </div>
<% end %>
<% if @user_favorites.empty? %>
  <h2>お気に入りはありません</h2>
<% end %>
<%= link_to 'トップページに戻る', root_path %>